### ISSUE TITLE
Unable to create lock file at /run/container-management/lock Error: no such file or directory 

### ISSUE THREAD

**Issue by mikehaller** [eclipse-kanto/container-management#100]
I've been trying to reconfigure the home_dir and exec_root directories.

It seems that the location of the lock file is not considered and container-management tries to create the lock in a non-configured location (`/run/container-management`), which is derived from the location of the unix socket for the grpc server.

Unfortunately, the target location is not automatically created by default, as it *assumes* to be the same as one of the `exec_root_dir` locations.

Also the mix use of `/run` and `/var/run` is somehow confusing in the example template of the config.json.

Error message:
```
time="2022-11-29T14:51:09.652642392Z" level=error msg="[container-management][daemon_start.go:106][pkg:main]
[func:runDaemon]  unable to create lock file at /run/container-management/lock \n\t Error: no such file or directory "
```

For reference the config.json which produces the problem:
```
{
    "manager": {
        "home_dir": "/data/var/lib/container-management",
        "exec_root_dir" : "/data/var/run/container-management",
        "default_ctrs_stop_timeout" : 5
    },
    "containers": {
        "exec_root_dir": "/data/var/run/container-management",
        "home_dir": "/data/var/lib/container-management"
    },
    "network": {
        "home_dir": "/data/var/lib/container-management",
        "exec_root_dir": "/data/var/run/container-management"
    },
    "log": {
        "syslog": true
    },
    "things": {
        "enable": true
    }
}
```
Note that the location of the grpc_server address path has *not* been changed.

**Comment by k-gostev** [comment]
I will take a look, please assign me.
