### ISSUE TITLE
Support usage of encrypted container's images

### ISSUE THREAD

**Issue by dimitar-dimitrow** [eclipse-kanto/container-management#12]
Incorporate [imgcrypt](https://github.com/containerd/imgcrypt) features to support usage of encrypted container's images. This will allow clients to protect their proprietary information at the registry level. Some common use cases for containers' image encryption:
- Protect sensitive data by storing an encrypted image on registry servers vulnerable to attacks
- Encrypted image with sensitive data could even be stored on public registry like Docker Hub
- With good key management, encrypted images can provide high assurance that only certain machines/users that have access to a key can actually use those images

**Acceptance:**
- Container management pulls, decrypts, unpacks and run encrypted images with the help of imgcrypt.
- It is possible to configure decrypt keys per container and globally on daemon start.
- The coresponding unit testing is done.
- The relevant user documentation is provided

**Tasks:**
- #16

**Comment by konstantina-gramatova** [comment]
The user documentation regarding the available configurations to use encrypted images and configure them both per container and for the daemon is already available in:
* [Container configuration - Image - decryption section](https://websites.eclipseprojects.io/kanto/docs/references/containers/container-config/)
* [Manager configuration - Runtime section](https://websites.eclipseprojects.io/kanto/docs/references/containers/container-manager-config/)
