### ISSUE TITLE
Change container names in the CLI IT

### ISSUE THREAD

**Issue by k-gostev** [eclipse-kanto/container-management#126]
Currently almost all containers that are being created are using the same name `test-it`. This leads to at least two downsides.
1. If one test fails, a lot of containers will leak because the clean up is done by name and currently with the kanto-cm CLI there is no way to delete multiple containers with the same name.
2. Parallel execution of tests is not possible for the same reason.

The containers test names should be changed to use the test case names.

**Comment by daniel-milchev** [comment]
I'll have a look at this.
