### ISSUE TITLE
Containers (e.g. Databroker CLI and python) are still in mode running even after quit command

### ISSUE THREAD

**Issue by ehb2hi** [eclipse-kanto/container-management#183]
We tested Kanto with the two containers  Databroker CLI and python. This behaviour is observed with the both.

Here for example the steps used for testing pyton container:
 
```shell
# kanto-cm create --name python --t --i --privileged docker.io/library/python:3.8.16-slim-bullseye
# kanto-cm start --name python --a --i
... quit()
# kanto-cm list
...
1b6ea656-d32b-453a-a0e0-1b0fafcae69f    |python                                 |docker.io/library/python:3.8.16-slim-bullseye                                  |Running        |2023-07-19T16:55:26.322020329Z  |0             |
# kanto-cm stop -n python -f  <---
# kanto-cm list
...
1b6ea656-d32b-453a-a0e0-1b0fafcae69f    |python                                 |docker.io/library/python:3.8.16-slim-bullseye                                  |Stopped        |2023-07-19T16:57:20.739670789Z  |137   <---        |

```

**Comment by dimitar-dimitrow** [comment]
Hello Brahim,

the default restart policy of a container is _unless-stopped_ which means that the container is automatically re-started, when you exit using _quit()_. That is why it is shown as running on the first list command output. You can configure the restart policy upon container creation or update it using the CLI:
```shell
# kanto-cm create --name python --t --i --privileged --rp no docker.io/library/python:3.8.16-slim-bullseye
# kanto-cm update -n python --rp no
```
When issuing stop command by default the container management sends SIGTERM signal to the process. However the container process does not seem to handle SIGTERM within the default timeout(30s). Than the container management re-tries with SIGKILL as the force flag is set, which results in exit status code of 137. The signal to be initially send and the timeout are also configurable via flags.

I hope that the behavior is now clear. If you have any further questions, please comment below.

**Comment by ehb2hi** [comment]
Hello Dimitar,

Thank you for your support.

Yes that is the correct solution for our problem and this ticket can be close.
