### ISSUE TITLE
Removed container is restored after reboot

### ISSUE THREAD

**Issue by LudwigWeise** [eclipse-kanto/container-management#195]
**Please note:** I'm not sure, if the below described issue is a bug or feature. Please check and reject the issue on your decision.

**Precondition:**
- Owasys owa5x HW (A12Y1D) flashed with RedEdgers distro v2.1.1 (Red Edgers 3.0 (kirkstone))

**Test steps:**
1. list containers
2. remove _self-update-agent_ with option forced (-f) [command "_kanto-cm remove -f -n self-update-agent_"]
3. list containers and image
4. reboot
5. list containers

**Results:**
- after step 4/5 the container _self-update-agent_ has been restored

**Expectation:**
- after step 4/5 the container _self-update-agent_ is **not** restored and step 2 removes also the image in cache.

**Comment by stoyan-zoubev** [comment]
@LudwigWeise
How is your container created? Is it automatically created by the Kanto CM deployment service? If yes, and its container descriptor file remains in the deployment service directory, then it is expected that the container is recreated upon restart of the container management service. This is exactly the feature of the deployment service.

**Comment by LudwigWeise** [comment]
You are right. After removing the descriptor file, container is no longer restored after reboot (only the image seems to be restored somehow).

Please close this issue and sorry for bothering you with this issue!

**Comment by stoyan-zoubev** [comment]
Container image should not be restored by Kanto CM. Rather it is not deleted with the removal of the container instance.
The removal of container images can be controlled by the container management image_expiry config property. By default, it's value is 31 days. If you need that Kanto CM removes the container image too please adjust the Kanto CM configuration.
More info - https://eclipse.dev/kanto/docs/references/containers/container-manager-config/
