### ISSUE TITLE
Add the option to remove all containers

### ISSUE THREAD

**Issue by daniel-milchev** [eclipse-kanto/container-management#205]
It would be convenient to be able to remove all containers at once. For example add:
```shell
kanto-cm remove -all
``` 
The point is that when you have to remove many containers one by one it can easily get tedious.

**Comment by k-gostev** [comment]
Removing all containers at once in random order is a bit harsh and could lead to multiple issue and can potentially have more downsides that benefits. What could be quickly implemented and be convenient is to remove all containers with the same name.
WDYT @dimitar-dimitrow

**Comment by dimitar-dimitrow** [comment]
I think that it is save to remove all non running containers using an _all_ flag. If the user insist on removing all containers(with running status as well) then the _force_ flag should also be specified. The _force_ flag would make the harshness of the operation visible to the user.

If the use case is to remove all containers with the same name, we should specify some filter flag as _all_ implies that the operation would be executed against every container. Using both _name_ and _all_ flags to remove all containers with some name does not seem intuitive to me.

**Comment by k-gostev** [comment]
I know this will be used usually with test scenarios, but still my main concern is that our current implementation of remove does not send SIGKILL immediately, which can make the process to hang a lot. Also, the combination of `--all --name` can lead to misunderstanding and someone may think that all containers with the given container name will be deleted.

So to summarise:

`kanto-cm remove --all` will remove all not running containers, so not all at all
`kanto-cm remove --all --force` will remove everything, no SIGKILL and very slow process
`kanto-cm remove --all --name` ?

**Comment by dimitar-dimitrow** [comment]
A _time_ flag could be added to mitigate the slow sending of SIGKILL. The combination of `--all --name` should be forbidden and a descriptive error must be returned. The description of the _all_ flag must describe that it can only be used in conjunction with _force_ and _time_ flags.

`kanto-cm remove --all ` will remove all non running containers. It is fine to leave the running ones as the default execution of _remove_ with a single running container does not remove it as well.
`kanto-cm remove --all --force` will remove everything, SIGKILL will be send after a default amount of time
`kanto-cm remove --all --force --time` will remove everything, SIGKILL will be send after the provided time

**Comment by k-gostev** [comment]
It is unnecessarily complicated IMO. If we are going with this lets just use only `kanto-cm remove --all` send a warning back + confirmation request and then purge all with immediate SIGKILL.

**Comment by daniel-milchev** [comment]
I looked into what options similar services provide, such as Podman, Docker and Kubernetes.

- Podman has the closest implementation to what I suggested, where they have the "--all" flag simply [remove](https://docs.podman.io/en/stable/markdown/podman-rm.1.html) all containers. It can also be used with the --force flag, so it removes everything regardless of the run state.

```shell
# Remove all containers regardless of the run state
podman rm -f -a
``` 
 - Docker on the other hand has a whole different command for mass deletion - "[prune](https://docs.docker.com/engine/reference/commandline/container_prune/)" which removes all **stopped** containers.
```shell
docker container prune [OPTIONS]
``` 
 - Kubernetes is a little bit different, but I still decided to look into what it offers. They have the ["delete"](https://kubernetes.io/docs/reference/kubectl/#:~:text=file%20or%20stdin.-,delete,-kubectl%20delete%20(%2Df ) command, which also has an "--all" flag.
```shell
# Delete all pods, including uninitialized ones.
kubectl delete pods --all
``` 
In my personal opinion, having such a flag in this service can be quite useful and time-saving.

**Comment by k-gostev** [comment]
In a joint sync between me, @daniel-milchev and @dimitar-dimitrow we decided to do the following:
 - Timeout should be added to the remove command
 - List command should be extended with filters and `quiet` flag, which will not print the table, but only the container IDs.
After that the `remove` and `list` commands would be able to be combined in a single command like:
```shell
kanto-cm remove $(kanto-cm list --filter status=stopped -q)
```
