### ISSUE TITLE
Deployment only out of .json files

### ISSUE THREAD

**Issue by OlavHerbst** [eclipse-kanto/container-management#222]
We detected that after editing a container deployment Json file the container is running twice. The reason is that the backup file created by text editor vim is also evaluated by the container-management. The log shows that it reads every file in deployment subdir. not only the files with suffix .json. Example:

ls -1a /etc/container-management/deployment/
.
..
self-update-agent.json
self-update-agent.json~     <-- created by vim
.self-update-agent.json.un~  <-- binary created by vim, not listed with ls
vehicle-update-manager.json

Suggestion to avoid this: Kanto should only evaluate the Json files with file extension .json for container deployment.

**Comment by k-gostev** [comment]
thanks @OlavHerbst  for reporting this bug, we will check it out and try to resolve it soon
