### ISSUE TITLE
Podman runtime support in container-management

### ISSUE THREAD

**Issue by kennyggd** [eclipse-kanto/container-management#223]
I have a proposal for adding runtime support for Podman. But i am not sure whether if it is a feature for container-management or suite-connector or both.

**Background**:

- We are currently introducing Podman and systemd into a target device to manage rootless containers and pods as systemd user services.
- "Basic" images are pre-loaded into host image as tarball via rauc bundle deployment (including kernel and filesystem updates, etc) and loaded into Podman runtime via podman load during runtime.
- In preparing the rauc bundle, we used podman to generate systemd user service files and include them into filesystem during rauc bundle update.
- systemd will start user services during bootup.
- user service file include cpu and memory limits via podman options.

**Use cases** are that:

1. Deployment: we wanted to have support of Kanto in terms of using podman for an alternative method to trigger update original images and trigger deploy of additional images to target device from a backend.
2. Resource-control: Additionally, we also want to explore if possibility of Kanto in changing systemd services and changing the resource limits that are originally defined.

**Comment by k-gostev** [comment]
Hi, @kennyggd, currently the whole Kanto team is on vacation for the holiday season. Please expect more activity in January, especially since your proposal is not trivial and would spark a lot of discussions.

**Comment by kennyggd** [comment]
Happy New Year @k-gostev and hope the team had a great holiday.
Sending this message here to start the spark of discussions again and would like to know your thoughts as well.

**Comment by k-gostev** [comment]
Hi @kennyggd, sorry for the delay. At this point our focus is on the cloud connectivity and OTA updates. As this is a major and resource consuming development I can't promise that the Kanto team would pick this topic any time soon.

What would be the benefits from edge point of view compared to the current implementation with containerd? Which features currently are missing, so you would like Podman to be integrated with the current Kant architecture?

**Comment by k-gostev** [comment]
closing as stale
