### ISSUE TITLE
Starting a container with config "network_mode" 

### ISSUE THREAD

**Issue by MilenaJaentgen** [eclipse-kanto/container-management#55]
I want to start a container in Eclipse Kanto by using a script similar to the python script https://github.com/eclipse-kanto/kanto/blob/main/quickstart/hono_commands.py but it should be configured to use the network type ,,host" instead of the default ,,bridge".

I already know, that I can add a ,,config" value in the corresponding json and use the variable ,,createWithConfig" instead of ,,create". An example for that would be:

```
{"topic": "tenant/device:edge:containers/things/live/messages/createWithConfig",
  "headers": {
        "content-type": "application/json",
        "correlation-id": "$correlation_id",
        "response-required": true
  },
  "path": "/features/ContainerFactory/inbox/messages/createWithConfig",
  "value": {
       "imageRef": "docker.io/library/influxdb:1.8.4", 
       "name": "influxdb",
       "config": {"domainName": "influxdb-domain", "privileged": true},
       "start": true
   }
}
```

After I read the documentation https://websites.eclipseprojects.io/kanto/docs/references/containers/container-config/ I guessed there also must be the opportunity to update the value ,,network_mode". But when I add ,,network_mode" in the ,,config" part, .i.e.

`"config": {"domainName": "influxdb-domain", "privileged": true, "network_mode": "host"},`

the value ,,network_mode" is not changed in the configuration of the container.

I would be very grateful if you could tell me which is the correct network configuration here.

**Comment by dimitar-dimitrow** [comment]
@MilenaJaentgen there are limited configuration options available through the ContainerFactory feature. You can see in the Vorto model what are the supported configurations - [here](https://github.com/eclipse/vorto/blob/development/models/com.bosch.iot.suite.edge.containers-Configuration-1.2.0.type/model.datatype). The "network_mode" is not part of it.

To have control over the full set of possible container configurations you could use the SoftwareUpdatable feature of the edge:containers device. Unfortunately the documentation is still under developing and currently there is only [how-to guide](https://websites.eclipseprojects.io/kanto/docs/how-to-guides/update-software/) for using the SoftwareUpdatable feature of the main device that enables the [Software Update](https://websites.eclipseprojects.io/kanto/docs/concepts/software-update/) functionality. 

However you can tweak [hono_commands_su.py](https://github.com/eclipse-kanto/kanto/blob/main/quickstart/hono_commands_su.py) by providing a config.json file as artifact. This file must contain the container configuration as per this [template](https://websites.eclipseprojects.io/kanto/docs/references/containers/container-config/#template). The install operation of the SoftwareUpdatable feature of the edge:containers device would create and start the container. In your case the config.json would be something like this:
```
{
  "container_name": "influxdb",
  "image": {
    "name": "docker.io/library/influxdb:1.8.4"
  },
  "domain_name": "influxdb-domain",
  "host_config": {
    "network_mode": "host",
    "privileged": true
  }
}
```

If any additional guidance is needed, I would be happy to help!

**Comment by dimitar-dimitrow** [comment]
@MilenaJaentgen such inconsistencies when creating containers via different interfaces would be cleared as part of #58. So I am closing this issue. If you need something else on the topic feel free to comment in the new issue or open a new one.
