### ISSUE TITLE
Encryption check failing for zstd-compressed images 

### ISSUE THREAD

**Issue by ttttodorov** [eclipse-kanto/container-management#60]
`zstd` is in the process of [being formalized in the OCI images spec](https://github.com/opencontainers/image-spec/issues/803) and is yet to be supported by e.g. [Moby regarding distribution via image registries](https://github.com/moby/moby/issues/28394#issuecomment-1176521516). Containerd already provides support for it via using the newly introduced `MediaType application/vnd.oci.image.layer.v1.tar+zstd `. 

The current Kanto container management component uses [imgcrypt](https://github.com/containerd/imgcrypt)'s library to perform a mandatory image encryption check based on the image's metadata and the configuration provided for using the image. Trying to spin up even a simple container using a non-encrypted zstd-compressed image, though, currently fails with the following error:

```
Error: rpc error: code = Unknown desc = you are not authorized to use this image: bad/unhandled MediaType application/vnd.oci.image.layer.v1.tar+zstd in encryptChildren
```

To reproduce the issue one can use [skopeo](https://github.com/containers/skopeo) to change the compression of a simple `hello-world` image and then push it to a private/[local registry](https://docs.docker.com/registry/), e.g.:

1. Use [skopeo copy](https://github.com/containers/skopeo/blob/main/docs/skopeo-copy.1.md) to create a zstd-compressed image and push it locally:

```
$ skopeo copy --dest-compress-format=zstd docker://hello-world docker://<some-plain-http-local-ip:port>/hello-world-zstd:latest --dest-tls-verify=false
```
2. Use [skopeo inspect](https://github.com/containers/skopeo/blob/main/docs/skopeo-inspect.1.md) to check the result pushed image compression:
```
$ skopeo inspect --raw docker://<some-plain-http-local-ip:port>/hello-world-zstd:latest --tls-verify=false | jq -r '.layers[].mediaType'
```

**Comment by k-gostev** [comment]
I can check this, please assign me to this issue if possible.

**Comment by k-gostev** [comment]
I have opened an issue in `contained/imgcrypt`: https://github.com/containerd/imgcrypt/issues/95
