### ISSUE TITLE
Implement signed images verification

### ISSUE THREAD

**Issue by konstantina-gramatova** [eclipse-kanto/container-management#67]
All used container images must undergo a signature verification (if signed) based on the provided verification data. If the verification fails, running a container instance using such an image must be aborted with the appropriate error.

The verification has to be implemented integrating [sigstore](https://www.sigstore.dev/)'s [Cosign](https://github.com/sigstore/cosign).
If a global daemon's configuration is applicable, it has to be covered as well.

**Comment by dimitar-dimitrow** [comment]
Signaturure would be pulled only on creation and would be deleted with their corresponding container images. Keys for verification could be provided globally - through container-management configuration, per container - through container configuration. Per container keys are prioritized.


|Image Signed|Global Keys|Per Container Keys|No Keys|
| --------------- |--------------- |--------------- |--------------- |
|No|Skip verification|Skip verification|Skip verification|
|Yes|Perform Verification|Perform Verification|Skip verification|

Skip verification - no verification is performed, container is created/started
Perform Verification - if verification fails, container is not created/started; if verification is successful, container is created/started.

**Comment by dimitar-dimitrow** [comment]
The focus has changed to implement signed image verification with notation-go instead of sigstore/cosign, for more information check this [comment](https://github.com/eclipse-kanto/container-management/issues/59#issuecomment-1820363855).
