### ISSUE TITLE
Align the exposed confgurations per container via all remote APIs

### ISSUE THREAD

**Issue by konstantina-gramatova** [eclipse-kanto/container-management#69]
Containers could be created via different interfaces. However, some configurations are missing in some of them, e.g. network mode configuration is missing when a container is created via ContainerFactory feature, as described in https://github.com/eclipse-kanto/container-management/issues/55. The target is to clear such inconsistencies.

**Comment by k-gostev** [comment]
### Container Configuration
#### Included in the [documentation](http://localhost:1313/kanto/docs/references/containers/container-config/) missing in [Vorto Model](https://github.com/eclipse/vorto/blob/development/models/com.bosch.iot.suite.edge.containers-Configuration-1.2.0.type/model.datatype)

|Property|Type|Comment|
|--------|-----|----------|
|keys|string[]|From Image|
|recipients|string[]|From Image|
|host_name|string||
|network_mode|string||

#### Included in in [Vorto Model](https://github.com/eclipse/vorto/blob/development/models/com.bosch.iot.suite.edge.containers-Configuration-1.2.0.type/model.datatype) missing in the [documentation](http://localhost:1313/kanto/docs/references/containers/container-config/)
 |Property|Type|
|--------|-----|
|openStdin|boolean|
|tty|boolean|

#### Missing everywhere
|Property|Type|Comment|
|--------|-----|----------|
|Hooks|Hook[]|Hooks is to perform on container start/stop, etc.|

**Comment by dimitar-dimitrow** [comment]
Vorto model PR in regards to the API updates - eclipse/vorto#2798
