### ISSUE TITLE
Connection of a container inside of the bridge network to the local mqtt-broker of Eclipse Kanto 

### ISSUE THREAD

**Issue by MilenaJaentgen** [eclipse-kanto/container-management#72]
I want to start a container by using the ContainerFactory feature like in [hono_commands.py](https://github.com/eclipse-kanto/kanto/blob/main/quickstart/hono_commands.py). This container should send messages through the local mqtt-broker of Eclipse Kanto to a backend, e.g. Eclipse Hono. For that my corresponding application which is written in python contains a paho client which should connect to the local mqtt-broker of Eclipse Kanto. 

When there would be the possibility to add a flag like "network_mode=host" when starting the container by using the ContainerFactory feature, my paho client could connect to "localhost" on port 1883 which is the address of the local mqtt-broker of Eclipse Kanto:

`paho_client.connect("localhost", 1883)`

Unfortunately at the moment there is no possibility for that like mentioned in [#58](https://github.com/eclipse-kanto/container-management/issues/58) and the answer in [#55](https://github.com/eclipse-kanto/container-management/issues/55) may not help since I don't know how the config.json file could be made reachable in Eclipse Kanto when it doesn't lie on a server which provides the protocols HTTP, HTTPS, FTP or SFTP.

So my question now is: What is the typical way to connect a client from such a container to the local mqtt-broker of Eclipse Kanto when I can not configure my container to use the host network instead of the bridge network? 

I would be very grateful if you could tell me which is the correct proceeding here.

**Comment by konstantina-gramatova** [comment]
@MilenaJaentgen thank you for posting this question as it is indeed a very important one! :blush: 
This is a very common IoT use case for containerized applications to utilize the Kanto local communication and benefit from the different brokering and connectivity management enhancements it provides. Having that said, we have already provided an out-of-the-box solution exactly for this use case:

There is a special "magic" reserved keyword in Kanto container management `host_ip` which runtime is resolved to the IP of the host device (and broker running there) on the `kanto-cm0` bridge network interface. To use this option, you can call the `createWithConfig` operation of the [ContainerFactory](https://github.com/eclipse/vorto/blob/development/models/com.bosch.iot.suite.edge.containers-ContainerFactory-1.2.0.fbmodel/model.functionblock) feature with an input like:

```
{
  "imageRef": "docker.io/library/influxdb:1.8.4",
  "name": "my-container-with-local-communication",
  "config": {
    "extraHosts": [
      "kanto_local_communication:host_ip"
    ]
  },
  "start": true
}
```
The `extraHosts` property adds the new host name with the resolved IP into the containers networking configuration so it's accessible inside it (more info about this property and the format of the strings in the array you can check out [here](https://websites.eclipseprojects.io/kanto/docs/references/containers/container-config/) under `extra_hosts`).

Then inside the application you can connect your Paho client using the host name `kanto_local_communication` like 
```
paho_client.connect("kanto_local_communication", 1883)
```

A fair note here is that the Mosquitto instance you have running on your edge device may need a little bit of configuration to listen to all interfaces on your device probably for anonymous connections as well, e.g. you would need to add these to `/etc/mosquitto/mosquitto.conf` and restart the service before calling ContainerFactory:
```
listener 1883 0.0.0.0 
allow_anonymous true
```
You can read more discussions about the same topic in the kanto-dev mailing list [here](https://www.eclipse.org/lists/kanto-dev/msg00013.html) - it would be great if you [subscribe](https://accounts.eclipse.org/mailing-list/kanto-dev) to keep in touch! :blush: 

Please, let me know if the info is helpful - I'd be happy to support you further in the use cases you are exploring and get them all up && running! :blush:

**Comment by konstantina-gramatova** [comment]
@MilenaJaentgen I hope you got the desired scenarios up && running :blush: I'll close this ticket for now as it looks like no further info is needed on our side but please feel free to reopen it and reach out if that's not the case and you need further support on the topic - we'd be happy to help out :blush:

**Comment by MilenaJaentgen** [comment]
Yes, thank you very much for your great help! It works very well now :)

**Comment by konstantina-gramatova** [comment]
Great! :blush:  No doubt the topic you raised is an important one, thus, a great candidate to enrich [Kanto's How-to guides](https://websites.eclipseprojects.io/kanto/docs/how-to-guides/) with it to make the shared info more easily accessible - it's on Kanto's improvements list now :heavy_check_mark:
